### ISSUE TITLE
USER STORY: Read Snapshot Details

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#16]
## EPIC: #15 

As a **user** I can **view a snapshot detail page** so that **I can read the full description of the snapshot and any associated comments and samples**

## Acceptance Criteria

* Any text description text context should appear under the snapshot image and title
* Associated samples should appear below snapshot
* Any associated comments should be stacked below the snapshot and make use of infinite scrolling to ensure they keep loading as the user scrolls 

## Tasks

* [x] Create SnapshotPage. Make use of the useEffect hook to fetch and setSnapshot based on a specific snapshot id.  This id should be retrieved and stored with the ```useParams()``` hook, which will read the id specified in the URL.  Add id to the useEffect dependency array to ensure this hook runs every time the id changes.
* [x] Include the Snapshot component in the return statement.  Spread the retrieved snapshot and pass as a prop.
* [x] Also retrieve associated comments, filtered using the snapshot id.  Spread these comments into the Comment component
* [x] Use react-infinite-scrolling-component and wrap it around the Comment component.
