### ISSUE TITLE
USER STORY: Create Comment

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#18]
## EPIC: #15 

As a **logged in user** I can **comment on another user's snapshot** so that **I can share my thoughts and interact with the Rewind community**

## Acceptance Criteria

* A comment text field and submission button should appear below the snapshot 
* Once posted, comments should appear below with the most recent appearing first
* Attached to each comment should be details of when it was posted and a link to the profile associated with the comment

## Tasks

* [x] Add a CommentCreateForm to the src/pages/comments
* [x] Make use of useState hook to store and set errors.
* [x] Write handleChange function to handle changes to the form state
* [x] Write handleSubmit function that saves the form data and posts this data to the /comments/ DRF API endpoint
* [x] To ensure that new comments are instantly reflected underneath the snapshot, ensure that within the handleSubmit function, setComments is called and updated with most recent data.
* [x] Also use setSnapshot to increment associated value for comments count by 1
* [x] return form and set onSubmit attribute to the handleSubmit function. Include a text area input and and use the onChange attribute to call the handleChange function
