### ISSUE TITLE
USER STORY: Responsive Navbar

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#2]
## EPIC: #1 

As a **user** I can **access a navbar on every page** so that **navigation of the site is intuitive**

## Acceptance Criteria

* Navbar appears at the top of every page.
* Nav links are collapsed on mobile devices and accessed via a hamburger toggle icon at the top right of the screen

## Tasks

* [x] Add NavBar.js to components folder in src directory
* [x] Create functional component using 'rafce' ES7 snippet
* [x] Import NavBar component into App.js
* [x] Add NavBar component inside <div className="App">
* [x] Use a react bootstrap navbar as a starting point and modify for project purpose (be sure to import required bootstrap components)
* [x] Import logo and add as image inside the Navbar.Brand component
* [x] Add css styling.  Any styles that may be used elsewhere in the project should go in the App.module.css file within the src folder.  Any style specific to the navbar should go in a NavBar.module.css within a styles folder in the src directory.
