### ISSUE TITLE
USER STORY: Delete Comment

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#20]
## EPIC: #15 

As a **logged in user** I can **delete my own comments** so that **I can control whether a previous comment remains visible to other site users**

## Acceptance Criteria

* A delete icon should appear next to any comments owned by the currently logged in user
* Clicking on the delete button should delete the comment and remove it from the list of comments below the snapshot

## Tasks

* [x] Create handleDelete function within the Comment component that sends a delete request to the comments API endpoint, specifying a specific comment id.
* [x] If the request is successful, use setSnapshot (that has been passed to the Comment component as a prop), to decrease the comment count for the associated snapshot by 1.
* [x] Use setComments (also passed as a prop to the Comment component) alongside a filter to remove the comment that has just been deleted from comments.  This ensures that deletion of a comment will be reflected immediately rather than having to refresh the page.
* [x] Pass the handleDelete function as a prop to the EditDelete component.  In the Edit Delete component, set the onClick attribute of the trash can icon to call the handleDelete function.
