### ISSUE TITLE
USER STORY: Recommend Snapshots

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#22]
## EPIC: #21 

As a **logged in user** I can **recommend a snapshot** so that **I can show my appreciation of another user's post and encourage others to view it**

## Acceptance Criteria

* Whenever a snapshot post is displayed on the site, a clickable 'recommend' icon should always appear with the post.  The total number of recommendations for the snapshot should also be communicated to the user.
* Clicking on the recommend icon should change the appearance of the icon to communicate to the user that the post has been successfully recommended.  The sum of total recommendations should be displayed next to the recommend icon and incremented by 1 each time a new recommendation is added.
* Clicking on a recommend icon when the logged in user has already recommended the snapshot should change the appearance of the icon, to communicate to the user that the recommendation has been removed.  The sum of total recommendations should be reduced by 1 to reflect the removal of the recommend.
* Non logged in users should not be able to recommend a snapshot.  To provide good user experience, they should be provided with feedback if they attempt to do this and signalled towards the 'log in' link

## Tasks

* [x] Define handleRecommend function in Snapshot component which makes a post request to the /recommendations/ API endpoint.  Specify the snapshot id that this recommendation should be attached to as part of the request.   use setSnapshots to increment recommendations_count by 1 and also set the value for recommendation_id
* [x] Define handleUnrecommend function in Snapshot component which makes a delete request to the / recommendations/ API using a specific recommendation_id.  Use setSnapshots to decrease recommendations_count by 1 and set recommendation_id to null for that specific snapshot.
* [x] Use ternary statement within the return statement of the Snapshot component to check if the user is logged in.  If they are, check whether user is the owner of the snapshot, and if so use Bootstrap overlay trigger to inform that they cannot recommend their own snapshot. If they do not own the snapshot, check if there is a recommendation id attached to the snapshot.  If there is display a fontawesome solid thumbs up icon with the handle Unrecommend function passed to the 'onclick' attribute.  If there is no recommendation_id, display a regular thumbs up icon with the handleRecommend function passed to the 'onclick' attribute.  Finally, if the user is not logged in, use Bootstrap overlay trigger to inform them that they must log in to recommend a snapshot.
