### ISSUE TITLE
USER STORY: Pin Snapshots

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#23]
## EPIC: #21 

As a **logged in user** I can **pin any snapshots of interest while browsing the site** so that **I can build a list of posts to return to later**

## Acceptance Criteria

* A pin icon should be displayed for any snapshots displayed to logged in users
* The pin icons should change in appearance to signal that the snapshot has been pinned
* The user should also have the ability to un-pin any snapshots once they have viewed them
* All pinned snapshots belonging to the logged in user should be displayed on their 'pinboard' page (accessible from a link in the navbar)
* Removing a pin from a snapshot on the pinboard page should update the page so that specific snapshot is no longer visible.

## Tasks

* [x]  Define handlePin function in Snapshot component which makes a post request to the /pins/ API endpoint. Specify the snapshot id that this pin should be attached to as part of the request. use setSnapshots to set the value for recommendation_id (so this id is now attached to the specific snapshot).
* [x] Define handleUnpin function in Snapshot component which makes a delete request to the /pins/ API endpoint using a specific pin_id. Use setSnapshots to set pin_id to null for that specific snapshot.
* [x] Use && conditional statement within the return statement of the Snapshot component to check if the user is logged in.  If the they are, check if there is a pin id attached to the snapshot. If there is display a fontawesome solid bookmark icon with the handleUnpin function passed to the 'onclick' attribute. If there is no pin_id, display a regular bookmark icon with the handlePin function passed to the 'onclick' attribute.  If the user is not currently logged in, the bookmark icon will not be displayed.
* [x] In the handleUnpin function once the delete request has been sent to the API endpoint, use a filter as part of setSnapshots to make sure only snapshots with a pin_id are displayed. (This ensures that if a user removes a pin from a snapshot on their pinboard page, this change will be reflected immediately rather than having to refresh the page.
