### ISSUE TITLE
USER STORY: Follow / Unfollow Profiles

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#29]
## EPIC: #24 

As a **logged in user** I can **choose to follow profiles that are posting interesting content** so that **I can be updated with more of their posts in the future**

## Acceptance Criteria

* When a user is logged in, a 'follow' button should appear next to each suggested profile if the user is not already following that specific profile.
* When a user is logged in, a 'follow' button should appear on the profile pages of other users if the logged in user is not already following that specific profile
* Clicking the 'follow' button should increment the 'followed' stats by 1 on the profile page associated with the newly followed profile
* The 'following' stats on the profile page of the logged in user should increment by 1
* The reverse should be the case for any profiles that a logged in user is already following.  Buttons should display as 'unfollow' and the 'following' and 'followed' stats for relevant profiles should be decreased by 1.
* All posts relating to followed profiles should be displayed on the 'watching page', accessed via the nav link in the navbar.  These should be ordered by most recent first.

## Tasks

* [x] Define the handleFollow function in the ProfielDataContext file which sends a post request to the `/followers/` API Endpoint, and sets the id of the profile that has just been followed.
* [x] Expose handleFollow function ProfileDataContext.provider - pass as a value.  This will ensure that the Profile components have access to this function when a 'follow' button is clicked
* [x] In ProfilePage and Profile component, de-structure handleFollow when calling the useSetProfileData hook
* [x] In ProfilePage and Profile component, call the handleFollow function from the 'follow' button's onClick attribute, passing profile as an argument
* [x] Reflect changes on the client side by using setProfileData once the post request has been successfully submitted.  Map over the popularProfiles array /pageProfile array and for each profile, call a followHelper function (write this in utils.js file) which does the following:
   * [x] If the profile id matches the id of the clicked profile, increment the followers_count by 1 and set the following_id
   * [x] If the user is the owner of the profile, increment the following_count by 1
   * [x] Otherwise just return the profile 
* [x] Repeat steps above to create the handle Unfollow function in the ProfielDataContext file and unfollow Helper in utils.js.  The unfollowHelper should decrease followers_count and following_count by 1, and set the following_id to null.
