### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#3]
## EPIC: #1 

As a **user** I can **navigate the content of the site without the page refreshing** so that **content is accessed quickly and user experience is enhanced**

## Acceptance Criteria

* Clicking on nav links in the nav bar should direct the user to the requested page without the page refreshing

## Tasks

* [x] ```npm install react-router-dom@5.3.0```
* [x] Import BrowserRouter to index.js as 'Router'
* [x] Wrap App component in index.js file with Router
* [x] Import Switch and Route components to App.js
* [x] Create Switch within Container component (this holds all the routes)
* [x] Add Routes - use 'exact' prop so only urls that are exactly the same are matched.  The 'render' prop returns a Component to be rendered when the Route path is matched.
* [x] Import NavLink component into NavBar.js file and use this to wrap all links in the navbar.  Use the 'to' prop to indicate where the link should navigate to
* [x] Use activeClassName prop on NavLink component to indicate to the user which page they are currently viewing.
* [x] Add the 'exact' prop on the home Navlink to ensure this does not show as active when other pages are navigated to.
* [x] Add catch-all route to handle page not found error (below all other routes)
