### ISSUE TITLE
TASK: Profile Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#31]
## USER STORIES: 

* #25
* #26 
* #27
* #28 

## Tasks

* [x] Create the profiles app and register in the settings.py file
* [x] Create Profile model and add fields (reference database schema).
* [x] Use Django signals to automatically create an instance of Profile every time a new user is created.
* [x] Make migrations and migrate changes to the database.
* [x] Register Profile model in the admin.py file in order to access from the Django admin panel.
* [x] Create ProfileSerializer Class in the serializers.py file.  Additional fields to display in the JSON response:
  * [x] The owner's username
  * [x] is_owner boolean value 
  * [x] A list of era_preferences, displayed as their string representation
* [x] Define a get_following_id method to determine whether a logged in user is following an instance of Profile.  Return the id for the instance of Follower if the user is following another profile and None if they are not.  Return None if the user is logged out.  This value should be included in the ProfileSerializer as 'following_id'.
* [x] Write List and Detail views.  No need to provide ability to create an instance of profile as this is taken care of using signals.
* [x] Add urls for list and detail views
* [x] Include profiles urls in master rewind url patterns.
