### ISSUE TITLE
TASK: Authentication & Permissions

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#32]
## RELATED USER STORIES:

* #4
* #5 
* #7

## Tasks

* [x] Include the login and logout views from the Django REST Framework in the main rewind urls.py file
* [x] Create a permissions.py file in the rewind app and create a class called IsOwnerOrReadOnly.  Within this class, define a method called has_object_permission.  If the request method is 'safe' ie. GET, this should return True.  If the request method is not safe ie. PUT or DELETE, the has_object_permission method should return True only if the user owns the object, otherwise it should return False.  This prevents users updating or deleting instances of a model that do not belong to them .
* [x] Add permission_classes to any view where required and specify ```IsOwnerOrReadOnly``` if suitable.
