### ISSUE TITLE
TASK: Snapshot Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#33]
## RELATED USER STORIES:

* #9 
* #10 
* #11 
* #13 
* #14 
* #16 
* #17 
* #39 

## Tasks

* [x] Create the snapshots app and register in the settings.py file
* [x] Create Snapshot model and add fields (reference database schema).
* [x] Make migrations and migrate changes to the database.
* [x] Register Snapshot model in the admin.py file in order to access from the Django admin panel.
* [x] Create SnapshotSerializer Class in the serializers.py file.  Additional fields to include in the JSON response:
  * [x] The owner's username
  * [x] is_owner boolean value 
  * [x] The snapshot owner's profile id and profile image
* [x] Define a get_following_id method to determine whether a logged in user has recommended an instance of Snapshot.  Return the id for the instance of Recommendation if the user has recommended a snapshot and None if they have not.  Return None if the user is logged out.  This value should be included in the SnapshotSerializer as 'recommendation_id'.
* [x] Write List view using the generics ListCreateAPIView, with following functionality:
  * [x] Use the permissions class IsAuthenticatedOrReadOnly, to ensure only logged in users can create a new snapshot.
  * [x] Define the perform_create method, so every time a new snapshot is created it is associated with the logged in user.
* [x] Write Detail view using the generics RetrieveUpdateDestroyAPIView with following functionality:
  * [x] Use the permissions class IsOwnerOrReadOnly defined in ```rewind/permissions.py```, to ensure a user can only edit or delete a snapshot if they own it.  All users should be able to retrieve a specific snapshot by id.
* [x] Add urls for list and detail views
* [x] Include snapshots urls in master rewind url patterns.
