### ISSUE TITLE
TASK: Recommendation Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#35]
## RELATED USER STORIES:

* #22

## Tasks

* [x] Create the recommendations app and register in the settings.py file
* [x] Create Recommendation model and add fields (reference database schema).
* [x] Include 'unique_together' fields in Meta Class.
* [x] Make migrations and migrate changes to the database.
* [x] Register Recommendation model in the admin.py file in order to access from the Django admin panel.
* [x] Create RecommendationSerializer Class in the serializers.py file.  Additional fields to include in the JSON response:
  * [x] The owner's username
* [x] Write List view using the generics ListCreateAPIView, with following functionality:
  * [x] Use the permissions class IsAuthenticatedOrReadOnly, to ensure only logged in users can create a new recommendation.
  * [x] Define the perform_create method, so every time a new recommendation is created it is associated with the logged in user.
* [x] Write Detail view using the generics RetrieveDestroyAPIView with following functionality:
  * [x] Use the permissions class IsOwnerOrReadOnly defined in ```rewind/permissions.py```, to ensure a user can only delete a recommendation if they own it.  All users should be able to retrieve a specific recommendation by id.
* [x] Add urls for list and detail views
* [x] Include recommendations urls in master rewind url patterns.
