### ISSUE TITLE
TASK: Pin Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#36]
## RELATED USER STORIES:

* #23 

## Tasks

* [x] Create the pins app and register in the settings.py file
* [x] Create Pin model and add fields (reference database schema).
* [x] Include 'unique_together' fields in Meta Class to ensure a user cannot pin a snapshot twice.
* [x] Make migrations and migrate changes to the database.
* [x] Register Pin model in the admin.py file in order to access from the Django admin panel.
* [x] Create PinSerializer Class in the serializers.py file.  Additional fields to include in the JSON response:
  * [x] The owner's username
* [x] Write List view using the generics ListCreateAPIView, with following functionality:
  * [x] Use the permissions class IsAuthenticatedOrReadOnly, to ensure only logged in users can create a new instance of Pin.
  * [x] Define the perform_create method, so every time a new instance of Pin is created it is associated with the logged in user.
* [x] Write Detail view using the generics RetrieveDestroyAPIView with following functionality:
  * [x] Use the permissions class IsOwnerOrReadOnly defined in ```rewind/permissions.py```, to ensure a user can only delete a pin if they own it.  All users should be able to retrieve a specific instance of Pin by id.
* [x] Add urls for list and detail views
* [x] Include pins urls in master rewind url patterns.
