### ISSUE TITLE
TASK: Follower Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#37]
## RELATED USER STORIES:

* #29

## Tasks

* [x] Create the followers app and register in the settings.py file
* [x] Create Follower model and add fields (reference database schema).
* [x] Include 'unique_together' fields in Meta Class so a user cannot follow the same profile twice.
* [x] Make migrations and migrate changes to the database.
* [x] Register Follower model in the admin.py file in order to access from the Django admin panel.
* [x] Create FollowerSerializer Class in the serializers.py file.  Additional fields to include in the JSON response:
  * [x] The owner's username
  * [x] The 'followed' name
* [x] Write List view using the generics ListCreateAPIView, with following functionality:
  * [x] Use the permissions class IsAuthenticatedOrReadOnly, to ensure only logged in users can create a new instance of Follower.
  * [x] Define the perform_create method, so every time an instance of Follower is created it is associated with the logged in user.
* [x] Write Detail view using the generics RetrieveDestroyAPIView with following functionality:
  * [x] Use the permissions class IsOwnerOrReadOnly defined in ```rewind/permissions.py```, to ensure a user can only delete an instance of Follower if they own it.  All users should be able to retrieve a specific instance of Follower by id.
* [x] Add urls for list and detail views
* [x] Include followers urls in master rewind url patterns.
