### ISSUE TITLE
TASK: Era / Genre / Category Resources

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#38]
## USER STORIES: 

* #13 
* #25

## Tasks

For the era, genre and category resources carry out the following tasks:

* [x] Create the app and register in the settings.py file.
* [x] Create the model and add fields (reference database schema).
* [x] Make migrations and migrate changes to the database.
* [x] Register model in the admin.py file in order to access from the Django admin panel.
* [x] Create Serializer Class in the serializers.py file.  Display all fields from the corresponding model in the JSON response.
* [x] Write List View. Use ListCreate generic view to allow ability to list all instances of a model and create a new instance.
* [x] Write Detail View. Use RetrieveUpdate generic view to allow ability to retrieve an instance of a model by id and update an instance.
* [x] All views for the era, genre and category resources should only be accessible to staff users.
* [x] Add urls for list and detail views
* [x] Include list and detail urls in master rewind url patterns.
