### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#4]
## EPIC: <epic>

As a **user** I can **sign up and create a user account** so that **I can access additional site functionality only available to authenticated users**

## Acceptance Criteria

* Sign Up link should be displayed in the navbar to non logged in users 
* Form data should be validated on submission and users alerted to any errors.
* Feedback should be provided on how to correct any form errors.
* Users should be directed to the sign in form once an account has been created
* A profile instance should automatically be created for each new user
* Confirmation message required as feedback to user?

## Tasks

* [x] See the steps taken in issue #41 for connecting the frontend react app to the backend api in development mode
* [x] Install Axios library (this will tell the react app to send requets to the API)
* [x] Create api folder with in src directory.  
* [x] Create axiosDefaults.js file within api folder. Import axios.  **DO NOT DEFINE BASE URL YET WHILE IN DEVELOPMENT MODE AS IT CAN CAUSE ERRORS.  THIS WILL NEED TO BE SET WHEN IT COMES TO DEPLOYMENT**
* [x] Other axios settings:
     * [x] axios.defaults.headers.post["Content-Type"] = "multipart/form-data";
     * [x] axios.defaults.withCredentials = true; 
* [x] Import axiosDefaults to app.js
* [x] Within src directory, create a 'pages' folder and within this an 'auth' folder
* [x] Within 'auth' folder, create the file SignUpForm.js. Add basic structure and styling to this form.
* [x] Add SignUpForm component to signup route in App.js
* [x] Use react bootstrap as starting point and modify
* [x] create handleChange function for form events
* [x] add handleChange to each Form.Control component
* [x] Create handleSubmit function
* [x] Set Form component's onSubmit prop to the handleSubmit function that has just been created.
* [x] Use catch block in handleSubmit function to detect and display errors.
* [x] Display errors to user with bootstrap Alert component.
