### ISSUE TITLE
TASK: DRF Filtering

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#40]
## Tasks

* [x] Use annotate to add snapshots_count, followers_count and following_count to the queryset returned by the Profile List and Detail views.  Include ```distinct=True``` to these fields.
* [x] Add OrderingFilter to the Profile List view with required 'ordering_fields' specified.
* [x] Add snapshots_count, followers_count and following_count to ProfileSerializer and as fields in the Meta Class.
* [x] Use annotate to add recommendations_count and comments_count to the queryset returned by the Snapshot List and Detail views.  Include ```distinct=True``` to these fields.
* [x] Add OrderingFilter to the Snapshot List view with required 'ordering_fields' specified.
* [x] Add recommendations_count and comments_count to ProfileSerializer and as fields in the Meta Class.
* [x] Make snapshots searchable by adding the SearchFilter to the Snapshot List view.  Specify snapshot title, era, genre and category as search fields.
* [x] Install django-filter library
* [x] Implement the following filter functionality:
   * [x] Show profiles that are following a specified user
   * [x] Show profiles that are being followed by a specified user
   * [x] Show snapshots owned by users that a particular user is following
   * [x] Show snapshots that have been recommended by a particular user
   * [x] Show snapshots that are owned by a particular user
   * [x] Show comments for a specific snapshot
   * [x] Show snapshots for a specific era, genre or category
