### ISSUE TITLE
TASK: SETUP REACT PROJECT

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#41]
## EPIC: #1 

Setup a React project for development of the frontend. This should be part of a unified workspace alongside the DRF API.

## Tasks

* [x] Create frontend folder in root directory of workspace
* [x] Change directory to be inside the newly created frontend folder and run the following command from the terminal:
```
npx create-react-app . --template git+https://github.com/Code-Institute-Org/cra-template-moments.git --use-npm
```
* [x] Once all dependencies have been installed, ensure that you syill inside the frontend folder and run the command to remove files that already exist in the root directory:
```
rm -rf .git .gitignore README.md
```
* [x] Run the command ```npm start``` from the terminal to check that the basic React app is running.
* [x] Add the following to the Django env.py file:
     * [x] ```os.environ['DEBUG'] = '1'``` 
     * [x] ```os.environ['ALLOWED_HOST'] ='(insert gitpod development url)'``` (remove trailing slash from end of url)
     * [x] ```os.environ['CLIENT_ORIGIN'] ='https://(insert gitpod development url)'``` (remove trailing slash from end of url)
* [x] Add proxy to bottom of react package.json file:
```
"proxy": "http://localhost:8000/"
```  
* [x] Within the src folder of the frontend folder, create an api folder and within this create a `axiosDefaults.js' file with comment to remind not to set a separate baseURL until deployment, to prevent errors during development.
