### ISSUE TITLE
TASK: Sample Resource

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#42]
## RELATED USER STORIES:

* #14

## Tasks

* [x] Create the samples app and register in the settings.py file
* [x] Create Sample model and add fields (reference database schema).
* [x] Make migrations and migrate changes to the database.
* [x] Register Sample model in the admin.py file in order to access from the Django admin panel.
* [x] Define the approve_samples method in the admin.py file.
* [x] Create SampleSerializer Class in the serializers.py file.  Additional fields to include in the JSON response:
  * [x] The owner's username
  * [x] is_owner boolean value 
  * [x] The sample owner's profile id and profile image
* [x] Create SampleDetailSerializer Class which includes 'snapshot' field which references the snapshot id that the sample is associated with.
* [x] Write List view using the generics ListCreateAPIView, with following functionality:
  * [x] Use the permissions class IsAuthenticatedOrReadOnly, to ensure only logged in users can add a new sample.
  * [x] Define the perform_create method, so every time a new sample is created it is associated with the logged in user.
* [x] Write Detail view using the generics RetrieveDestroyAPIView with following functionality:
  * [x] Use the permissions class IsOwnerOrReadOnly defined in ```rewind/permissions.py```, to ensure a user can only delete a sample if they own it.  All users should be able to retrieve a specific sample by id.
* [x] Add urls for list and detail views
* [x] Include samples urls in master rewind url patterns.
