### ISSUE TITLE
USER STORY: Authentication Status

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#6]
## EPIC: #1 

As a **user** I can **see whether I am already logged in** so that **I am aware of my status and the features of the site I can access**

## Acceptance Criteria

* 'For You', 'Pinned' and 'Profile' should appear as links in the navabr, to indicate to the user that they have access to additional site functionality as a logged in user.
* If the user has uploaded their own profile picture, this should appear in the navbar rather than the default profile avatar.

## Tasks

* [x] Create custom context hook which stores current user state. (src/contexts/CurrentUserContext.js)
* [x] Write handle mount function to make call to API to retrieve and set the current user. 
* [x] Add useEffect to run the handleMount function on mount
* [x] In index.js file , wrap the App with the CurrentUserProvider component which has been defined in the CurrentUserContext.js file
* [x] Call custom useSetCurrentUser hook in SignInForm to update current user data on successful login
* [x] Call custom useCurrentUser hook in NavBar.js to display icons/ links relevant to a logged in user 
* [x] Use Axios interceptors to intercept requests and responses from API.  Response interceptor should listen for when a user's access token has required and refresh in the background.  Request interceptor should intercept any requests sent to the API by the user that requires information about the logged in user to work, and refresh the user access token before sending request.
* [x] Make use of useMemo hook in CurrentUserContext.js file, to attach interceptors before children mount.
* [x] Create a loggedInIcons variables containing links and icons to display for an authenticated user.  Use conditional operator for this.
* [x] Create Avatar component and associated css module, to handle display of profile image in navbar.  This can be used in other components as this profile image will appear elsewhere on the site.
