### ISSUE TITLE
USER STORY: Sign Out

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#7]
## EPIC: #1 

As a **user** I can **sign out from the site** so that **no one else using my device can access my account**

## Acceptance Criteria

* Sign Out link should be displayed in the navbar for authenticated users
* Users should maintain their logged in status until they choose to sign out
* Upon sign out, user returns to home page and navbar only displays links for unauthenticated user.

## Tasks

* [x] call useSetCurrent user hook in NavBar component
* [x] Define function called handleSignOut.  This should make a post request to the API logout endpoint and then set current user to null
* [x] Add onClick prop to sign out NavLink component which runs the handleSignOut function.
