### ISSUE TITLE
USER STORY: Homepage Snapshot Feed

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/rewind#9]
## EPIC: #8 

As a **user** I can **view all snapshots posted** so that **I can get an overview of the type of content available on the site and decide whether I would like to sign up**

## Acceptance Criteria

* A list of snapshots should appear on the site home page for all users
* Snapshots should be displayed using infinite scrolling so content continues to be loaded and presented to the user
* Snapshots should by default be ordered by 'most recent'

## Tasks

* [x] Create SnapshotsPage.  Make use of the useEffect hook to fetch and set snapshots based on the filter prop passed as an argument.  For the home page, no filter is necessary as all posts should be displayed.  Add `filter, pathname` to the useEffect dependency array to ensure this hook runs every time the path or filter changes.  This is necessary as the SnapshotsPage will not only serve the site home page, but also the pinned page which has a different route and filter.
* [x] hasLoaded state by default should be set to False and set to True once snapshot data has been retrieved.  Use this hasLoaded boolean value to determine whether a spinner should be displayed.  This ensures that the user is made visually aware that snapshots are still loading.
* [x] Iterate over the snapshot results using map and assign each one to to the Snapshot component.  Pass each a key with the value of the snapshot id.
* [x] If no results are returned, display an image and message letting the user know that no snapshots could be found.
* [x] Create Snapshot component with the following functionality:
  * [x] Establish the current user with the custom CurrentUserContext hook .  This will be used throughout the component to determine functionality and what elements to show.
  * [x] De-structure the snapshot prop that is passed in from the SnapshotsPage so these attributes are accessible when writing the return statement and handler functions.
* [x] Add the SnapshotsPage component to the home route in App.js"
* [x] Install react-infinite-scrolling-component and wrap it around the mapped snapshot results in SnapshotsPage.js.
* [x] Write the fetchMoreData function in a utils files, and call this from the InfiniteScroll `next` prop
